language: python
cache:
  pip: true
python:
- 3.6
dist: trusty
addons:
  apt:
    packages:
    - npm
before_install:
- pip install awscli --upgrade
install: npm install
script: make build
deploy:
  provider: script
  script: make deploy-staging-travis
  skip_cleanup: true
  on:
    branch: staging-continuous-deployment
env:
  global:
    - secure: GzCNhfSZe32yHeTh/5qGSxKK6MvHwhKoY7wyZVyXZ9ENRZoaKq8SJcEiwO+CsxZVv5i6KVQWDRA9So69otwR/EZB2g/nftIX3rirVaQv9FxIUVpDjfXT3X4AF9Z5qyHRZaud9eg+bRIEHIk148Orc54vX4SMpUdYU5aKE1xBzyfckc1vAP6+ushJQ6O037hLn0pmNIo58ysgvwO3pIzYs33pMXSitueoJI+bnbE0CFXJ7LpnymvYhhrEyGs6GzxfV6tVnYCpd34TPfUgHdXGuop0moMctq38vmA2O1yDA8/e4vJmDZEZGgMPRx9Z0Udxw+CIQ0wghRVDKG5q9ymprbv+OGQwjel8nS3rOfltAlqbow3Img7AmJNTRWhfA1TAOvThGzh9pevkK7uJxHC3N5edDh193muhz88aotFXNFnevBhbPSKCn4bPXmLShqH52xp4eBvykVayirFyJuc+TkGjYsodIY/t7SwiKDqckxTaJac/dd46LVr6usRjXcfXrVEvI1Fa616lRFbBEzO/dDQ7vsaW1SUq6YgGM7DS7dHiUMAAg5G3R2WIL8o06DcQWYR8TaG2xnkYx5XN/zQphWjog9S/4FCv8BmPCKiT7A9sEotLlyy09E+LqHkGfMJSStF2wgvtPo+VMZdZ1jmFEssGjKanaQ98KV/1gyJOZJI=
    - secure: vDNCy3s2LchveRznP5q2lO6ixKJgYPmI0K/63cwn9u1LLk9jOdAmY9VwTwT6lxaAdGGnet5pG2dOWGtDPAl7V0KLgtk8tC8D7KgcAO011Y0SbRa5s2o07XyKujEbc6wFCqkO/3Bvm99ZfjGojp6HpV2ckaMh/YLkeVSne0XiGY/HgzcckoDbdpmYvq4sYdwnrMiHdDty0RwXvsWpJsE05EW7VFXzTNpUN/CNLZpv9c3JMXAMNwDw7U3z2FjS/xK0o1KNLcsrt3fU9Gsol4x0oIrlkIWrosltoGpvsE8aZxhrnoCmzzwp/rV04sgf7+bLUlU9e4VQUKLiH4jdYQorwLKvdxbPG67rIFgn3vDHhG6LaJE1hNkmjV31Ra1eYybcGxnNFTnuoArtjm/lbqNMH+e3OdzylnZNbDdELI6wLWhztTVLqLmL8nKhNmcNynpQOqOc7tcXMPgwxrlqRTOKWMSg973N1keBbkZ00aSedCzm6kn0ayQ+TgzzhEoNLUZeZio5z1FY+c1UHf9A8bsAStK1UHGEqDwZ+vZzgOnNrlmwfs6HP8EFgI8BmYc5qo49XolWTNQIZVxLFwv9qHNAALcHgqvMfEC889Y28w7A7GTqsyB60orUqu/JQUWEuPFyirxo7aCFWW7KjdW3kpsUKSykYjBymeJd/RmSai82NuQ=
    - secure: MXxNk0Z2J/3yjs5njIXGX1nb05TBb7yG39u2D9rYVMNw1kPxDAVG0cAfDEQuDtpCap6OjY4lvEK2DrwlN5OlXz0eKEG5IxLlNJVrMcqqvcBrR5yOiQUaYG436kSs5qQCHstCKbyoirbEB+JtlWSvXCGS+aXZRGmZZ7dw+lmJRBUOxAYaj588FsmBGgAmJ2Wrl9ALwEjZX7qZHMFxgdEHsFRVuQfDWYfKhZWSyuPKdxyLCEMXLvnoaLZaYJzlWMzbtVm1jnpKfecGofqWdgMbU47UrhDfDpNkqJM6GZLGx13HMelWq+C/UWX/ipGB95QuiEnM+AsfPs6nOQ5V6WsEWpqc02F/8R7Segq4GPnvpIcjn95IqTnWOPGisfNjZlnHtKNOeHNFpdoTnYrLKP/izVgkVkDAYxrEyT5PYLN1HAHkZ5Jz9MiFOFIvHGmp7Sgkwr7voTict2TEhKUecLdpP3I8IWs5kxXkMO46rKYrz3PRmpv/6n+54OnRrCh1lmuMDn+K2IfEkrmh1yHzMk8gjVu/A8AuvbWIct63tAklz2iK68cXnjgH1xk5hVupFFvHTzKsMaP5YBoPh0DXQSsZFuzeIcXhGmLD4lEXZba1+hy4yBAqGjOBThMmKG2WIAkX2Hi6zpHR8PVXUIiylPxq2rYsOssupIdlvHneyRXbgN4=